version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  python_microservices:
    build:
      context: ./python_microservices
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Takes prio over .env in frontend
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
      - python_microservices

volumes:
  db_data: